--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/raditya743/FormAPII
branches:
- master
projects:
  FormAPII:
    path: ""
  libFormAPI:
    path: ""
    type: library
    model: virion
...
